### PR TITLE
Fix and test min versions build

### PR DESCRIPTION
**Pull request by newpavlov**

### CODE REVIEW

**Comment by tarcieri** [comment]
This isn't going to work with the `minimal-versions` script in the current form. I updated the open issue here:

https://github.com/RustCrypto/actions/issues/15

We can revisit this if the issues around `minimal-versions` are fixed upstream.

**Comment by newpavlov** [comment]
I think we should keep this issue open since min version build does not work for all crates in this repository. At the very least it should be fixed and checked manually.

**Comment by tarcieri** [comment]
@newpavlov it's unfixable without `minimal-versions` changes

**Comment by newpavlov** [comment]
Ah, I thought it was an issue, not PR.

**Comment by tarcieri** [comment]
A tracking issue would probably be good.

If things get fixed upstream this would work.

**Pull request closed without merging**
